export const PAGE_CONFIG = {
  HOME: '/',
  LOGIN: 'login',
  REGISTRATION: 'registration',
  PROFESSIONAL: 'professionals',
  SUPPORT_CENTER: 'support-centers',
  ACCOUNT: 'account',
  PROFILE: 'profile',
  CONCLUSION: 'conclusion',
  PROBLEMS: 'problems',
  PROCESSING_PROBLEMS: 'processing-problems',
  HISTORY_PROBLEMS: 'history-problems',
  USERS: 'users',
  ERROR: 'error',
};
